{
    "name": "Hospital Management",
    "version": "19.0.1.0.0",
    "summary": "Basic hospital management module",
    "category": "Healthcare",
    "author": "NerithonX Technologies",
    "license": "LGPL-3",
    "depends": ["base","mail"],
    "data": [
        'security/hospital_groups.xml',
        'security/ir.model.access.csv',
        'security/hospital_rules.xml',
        
        "views/patient_views.xml",
        "views/doctor_views.xml",
        "views/patient_menus.xml",
        'views/patient_report_templates.xml',
        'views/patient_report.xml',
        'views/appointment_views.xml',
        'data/patient_cron.xml',
        'data/patient_email_template.xml',
        'data/appointment_data.xml',
    ],
    "installable": True,
    "application": True,
}
